services:
  - type: web
    name: brotherhood
    env: node
    plan: free
    buildCommand: npm install && node script/build.js
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
