services:
  - type: web
    name: brotherhood
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
